/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class Main {

    public static void main(String[] args) {
        int last = 0, secondLast = 0, total = 0;
        for (int i = 1; i <= 100; i++) {
            if (i == 1) {
                last = i;
                secondLast = i-1;
                total = secondLast+last;
            }else {
                secondLast = last;
                last = total;
                total = secondLast+total;
            }
            System.out.print(total+", ");
        }
        for (int i = 1; i <= 20; i++) {
            if (i == 1) {
                last = i;
                secondLast = i-1;
                total = secondLast+last;
            }else {
                secondLast = last;
                last = total;
                total = secondLast+total;
            }
            if (total%2==0)
                System.out.println("Even Numbers: "+total);
        }
    }
}
